name: Nouvelle fonctionnalité (Data)
description: Décrivez la nouvelle fonctionnalité
title: "[Feature]: "
labels: ["➕ Nouvelle fonctionnalité", "📂 Datas"]
projects: ["neogroupemasprovence/3", "neogroupemasprovence/4"]
assignees:
  - cdupontgroupemasprovence
body:
  - type: dropdown
    id: environnement
    attributes:
        label: Type d'extraction
        description: L'extraction est ponctuelle, récurrente ou doit elle pouvoir être réalisée par un utilisateur ?
        options:
            - Ponctuelle
            - Récurrente
            - Le destinataire doit être autonome
        default: 0
    validations:
        required: true
  - type: textarea
    id: description
    attributes:
      label: Pourquoi ?
      description: Précisez la raison pour laquelle vous souhaitez cette nouvelle fonctionnalité.
      placeholder: Une description claire et concise de la raison (métier).
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Décrivez la solution que vous souhaitez. Pas de capture d'écran.
      placeholder: Une description claire et concise du comportement souhaité.
    validations:
      required: true
  - type: textarea
    id: contexte
    attributes:
      label: Contexte additionnel
      description: Donnez du contexte à votre demande
      placeholder: Ajoutez du contexte ou des captures d'écran ici
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Décrivez les alternatives que vous avez envisagé
      placeholder: Une description claire et concise des alternatives envisagées
  - type: checkboxes
    id: structure
    attributes:
        label: Structure des données
        description: En validant cette issue, je confirme que j'ai bien réfléchi aux données souhaitées. Toute modification entrainera la clôture de l'issue et l'arrêt des développements.
        options:
            - label: Je n'ai pas oublié de colonne
              required: true
            - label: L'ordre des colonnes est bien celui souhaité
              required: true
            - label: Le formatage des colonnes est bien celui souhaité
              required: true
  - type: checkboxes
    id: verification
    attributes:
        label: Vérification
        description: En validant cette issue, je confirme les points suivants
        options:
            - label: J'ai vérifié qu'il n'existe pas déjà une demande identique
              required: true
            - label: J'ai discuté de cette fonctionnalité avec l'équipe au préalable
              required: false
            - label: La fonctionnalité est en cours de réflexion
              required: false
