name: 🚀 Livraison d'une release
description: Checklist complète avant, pendant et après la livraison d'une release
title: "🚀 Livraison de la release X.Y.Z"
labels: ["📂 TMA"]
projects: [neogroupemasprovence/4]
assignees:
  - atournayre
body:
  - type: markdown
    attributes:
      value: |
        ## 🛠️ Le script de livraison a été mis à jour  
        ➡️ *Pensez à faire un `git pull` au préalable avant toute action !*

  - type: checkboxes
    attributes:
      label: ✅ Avant livraison
      options:
        - label: Vérifier que la branche `release/vX.Y.Z` est à jour avec `develop`
        - label: Vérifier que toutes les MR/PR nécessaires ont été mergées
        - label: Revalider les tests automatiques sur la branche de release
        - label: Mettre à jour la documentation utilisateur si nécessaire
        - label: S’assurer que les tâches de migration de données sont prêtes et testées
        - label: Vérifier les scripts de déploiement (Castor, Docker, etc.)
        - label: Confirmer la fenêtre de maintenance si nécessaire
        - label: Informer les parties prenantes (Support, Commerce, etc.)

  - type: checkboxes
    attributes:
      label: 🚚 Pendant la livraison
      options:
        - label: Lancer le script de livraison sur l’environnement cible
        - label: Appliquer les migrations de base de données
        - label: Vérifier les erreurs dans les logs applicatifs
        - label: Tester les pages critiques de l’application (login, dashboard, etc.)
        - label: Effectuer un test rapide de l’API (si applicable)

  - type: checkboxes
    attributes:
      label: 🧹 Après la livraison
      options:
        - label: Nettoyer les caches applicatifs (Symfony, reverse proxy…)
        - label: Confirmer que la supervision/monitoring est fonctionnelle
        - label: Lancer une tâche de synchronisation des données (si applicable)
        - label: Revenir vers l’équipe projet / client pour validation
        - label: Créer un tag Git `vX.Y.Z` si non encore créé
        - label: Mettre à jour la documentation de version / changelog
        - label: Supprimer ou archiver la branche de release si elle n’est plus nécessaire

  - type: textarea
    attributes:
      label: 💬 Commentaires
      description: Ajoutez ici tout commentaire utile ou retour spécifique à cette livraison
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 🔍 Points de contrôle transverses
      options:
        - label: Un **patch** a été créé ou n’est **pas nécessaire** pour cette version
        - label: La **liste des IPs autorisées** a été vérifiée
        - label: Certaines **permissions doivent être ajustées manuellement**
        - label: Le **catalogue** a été mis à jour ; une **synchronisation de la bibliothèque** est requise
